// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkCgNnqrBsgoaFN6_dWPsbL51Bsa0qS9E',
    appId: '1:735808254792:web:f50242768272e1f8a2f97d',
    messagingSenderId: '735808254792',
    projectId: 'serrainnova-79912',
    authDomain: 'serrainnova-79912.firebaseapp.com',
    storageBucket: 'serrainnova-79912.firebasestorage.app',
    measurementId: 'G-4NLZ77T95V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA3l-ngwbscZ_Irq4c7qokzFZDIs18m5c',
    appId: '1:735808254792:android:edd6cb514a386d74a2f97d',
    messagingSenderId: '735808254792',
    projectId: 'serrainnova-79912',
    storageBucket: 'serrainnova-79912.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo0AZ6l3Qca9t5vXv0-DBTCY8fwvZHrlY',
    appId: '1:735808254792:ios:a874711e4c5c5815a2f97d',
    messagingSenderId: '735808254792',
    projectId: 'serrainnova-79912',
    storageBucket: 'serrainnova-79912.firebasestorage.app',
    iosBundleId: 'com.example.serraInnova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo0AZ6l3Qca9t5vXv0-DBTCY8fwvZHrlY',
    appId: '1:735808254792:ios:a874711e4c5c5815a2f97d',
    messagingSenderId: '735808254792',
    projectId: 'serrainnova-79912',
    storageBucket: 'serrainnova-79912.firebasestorage.app',
    iosBundleId: 'com.example.serraInnova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkCgNnqrBsgoaFN6_dWPsbL51Bsa0qS9E',
    appId: '1:735808254792:web:6651614da38347a4a2f97d',
    messagingSenderId: '735808254792',
    projectId: 'serrainnova-79912',
    authDomain: 'serrainnova-79912.firebaseapp.com',
    storageBucket: 'serrainnova-79912.firebasestorage.app',
    measurementId: 'G-CSPGQB44ZT',
  );
}
